# Generated by Django 6.0.1 on 2026-01-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366F1', help_text='Hex color used for category badges', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('item_type', models.CharField(choices=[('item', 'Item'), ('title', 'Title'), ('gamepass', 'Game Pass'), ('event', 'Event Item')], default='item', max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary'), ('mythic', 'Mythic'), ('limited', 'Limited'), ('exotic', 'Exotic')], default='common', max_length=20)),
                ('value', models.PositiveIntegerField(help_text='Trade value points')),
                ('demand', models.PositiveSmallIntegerField(default=5, help_text='1-10 scale')),
                ('trend', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('falling', 'Falling')], default='stable', max_length=10)),
                ('is_limited', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('obtained_from', models.CharField(blank=True, help_text='Event, raid, or source', max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='values.category')),
            ],
            options={
                'ordering': ['-featured', '-value', 'name'],
            },
        ),
    ]
