# Generated by Django 6.0.1 on 2026-01-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0007_update_rarity_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('unobtainable', 'Unobtainable'), ('special_grade', 'Special Grade'), ('rare', 'Rare'), ('uncommon', 'Uncommon'), ('common', 'Common')], default='common', max_length=20),
        ),
    ]
