# Generated by Django 6.0.1 on 2026-01-20 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0013_profile_savedtrade_verificationtoken_inventoryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveIntegerField(help_text='Current value of the item')),
                ('requested_value', models.PositiveIntegerField(help_text='Requested new value')),
                ('reason', models.TextField(help_text='Reason for the value change request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_change_requests', to='values.item')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Superuser who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_value_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Value Change Request',
                'verbose_name_plural': 'Value Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
